spring:
  datasource:
    url: jdbc:h2:file:~/theter
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  jpa:
    properties:
      hibernate:
        hbm2dll:
          auto: update